package com.xplore.paymobile

import android.app.Application
import com.clearent.idtech.android.wrapper.ClearentWrapper
import com.xplore.paymobile.data.datasource.RemoteDataSource
import com.xplore.paymobile.util.Constants
import com.xplore.paymobile.util.EncryptedSharedPrefsDataSource
import dagger.hilt.android.HiltAndroidApp
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import timber.log.Timber
import javax.inject.Inject

@HiltAndroidApp
class App : Application() {

    private lateinit var encryptedPrefs: EncryptedSharedPrefsDataSource

    @Inject
    lateinit var remoteDataSource: RemoteDataSource

    override fun onCreate() {
        super.onCreate()
        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        }

        encryptedPrefs = EncryptedSharedPrefsDataSource(applicationContext)
        initSdkWrapper()

        // TODO: remove this after done, used only for test purposes
        foo()
    }

    private fun foo() = CoroutineScope(Dispatchers.IO + SupervisorJob()).launch {
        remoteDataSource.authToken = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ik16azNOelExTmpKR1F6UTNSRUk0T0VNNE1Ea3hOVE5DTnpsRk9VSkVSRGhGTVRSR05FUkRSUSIsInR5cCI6IkpXVCJ9.eyJEaXNwbGF5TmFtZSI6InBhdWxhIGJ1cmNoIiwiRW5hYmxlZCI6dHJ1ZSwiR2l2ZW5OYW1lIjoicGF1bGEiLCJPcmduYW1lIjoiQ2xlYXJlbnQgSFEiLCJTdXJuYW1lIjoiYnVyY2giLCJVc2VybmFtZSI6InBidXJjaCIsIlVzZXJwcmluY2lwYWxuYW1lIjoicGJ1cmNoQHFhLmNsZWFyZW50c3NvLm5ldCIsImF1ZCI6IjUzMjljYThjNTA1ZDExMjRlYmQwM2FkOCIsImJhZFB3ZENvdW50IjowLCJjbGllbnRfaWQiOiJwYnVyY2giLCJleHAiOjE2NzAzMzAzMjEsImlhdCI6MTY3MDMyOTQyMSwiaXNzIjoiY2hxcWFwZzAxLnFhLmNsZWFyZW50c3NvLm5ldCIsImp0aSI6Il9iOGUwNDMxZmNiMzI1YmM2YjYyMGViMDVkZWY3ZTU4MyIsIm1haWwiOiJkc2NoZXhuYXlkZXJAY2xlYXJlbnQuY29tIiwibWVtYmVyT2YiOlsiQ049TWFudWFsQmlsbGluZ0dyb3VwLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049SW50ZWdyYXRvclN1cHBvcnQsT1U9RW50ZXJwcmlzZVJvbGVzLE9VPVNlY3VyaXR5IEdyb3VwcyxPVT1DbGVhcmVudCBRQSxEQz1xYSxEQz1jbGVhcmVudHNzbyxEQz1uZXQiLCJDTj1JbnRlZ3JhdG9yQWRtaW4sT1U9RW50ZXJwcmlzZVJvbGVzLE9VPVNlY3VyaXR5IEdyb3VwcyxPVT1DbGVhcmVudCBRQSxEQz1xYSxEQz1jbGVhcmVudHNzbyxEQz1uZXQiLCJDTj1JbnRlcm5hbEFwaUFkbWluLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049Qm9hcmRpbmdBZG1pbixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPUJldGFVc2VyLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049Umlza1N1cGVyQWRtaW4sT1U9RW50ZXJwcmlzZVJvbGVzLE9VPVNlY3VyaXR5IEdyb3VwcyxPVT1DbGVhcmVudCBRQSxEQz1xYSxEQz1jbGVhcmVudHNzbyxEQz1uZXQiLCJDTj1wcmljaW5nVXNlcixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPU1lcmNoYW50QWRtaW4sT1U9RW50ZXJwcmlzZVJvbGVzLE9VPVNlY3VyaXR5IEdyb3VwcyxPVT1DbGVhcmVudCBRQSxEQz1xYSxEQz1jbGVhcmVudHNzbyxEQz1uZXQiLCJDTj1CaWxsaW5nQ3ljbGVBZG1pbixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPUludGVybmFsQXBpVXNlcixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPXByaWNpbmdBZG1pbixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPVJpc2tBZG1pbixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPUFjY291bnRNYW5hZ2VyLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049ZmluYW5jZUFkbWluLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049VXNlck1hbmFnZW1lbnRBZG1pbixPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPVZUQ2xlYXJlbnRBZG1pbmlzdHJhdG9ycyxPVT1FbnRlcnByaXNlUm9sZXMsT1U9U2VjdXJpdHkgR3JvdXBzLE9VPUNsZWFyZW50IFFBLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCIsIkNOPVZpcnR1YWxUZXJtaW5hbFVzZXIsT1U9RW50ZXJwcmlzZVJvbGVzLE9VPVNlY3VyaXR5IEdyb3VwcyxPVT1DbGVhcmVudCBRQSxEQz1xYSxEQz1jbGVhcmVudHNzbyxEQz1uZXQiLCJDTj1NZXJjaGFudEhvbWVVc2VyLE9VPUVudGVycHJpc2VSb2xlcyxPVT1TZWN1cml0eSBHcm91cHMsT1U9Q2xlYXJlbnQgUUEsREM9cWEsREM9Y2xlYXJlbnRzc28sREM9bmV0IiwiQ049VlRfQWNjb3VudEFkbWluaXN0cmF0b3JzLENOPVVzZXJzLERDPXFhLERDPWNsZWFyZW50c3NvLERDPW5ldCJdLCJub25jZSI6IjZhYzFiMjM5MjRhMTRmZmFiZGFkNWE3ZGVkMjJhNTc5IiwicHJpbmNpcGFsIjoicGJ1cmNoIiwic0FNQWNjb3VudG5hbWUiOiJwYnVyY2giLCJzdWIiOiJwYnVyY2giLCJ1c2VybmFtZSI6InBidXJjaCIsInZlcnNpb25Ud29Qcm92aWRlciI6ZmFsc2V9.z-hbv1Lxfqg-SOm6FH7L_IyuSuNRyFCpMnJ8Bkls4fP6BDGUhpFNAOxonmnas2gFEid4Dr44zoTbXoZzmFX4GqyHoUkAsXTQTcTm0y_8GKAsjHd9mve_KVln1f4LnaEjlHEGpN4m2_PhAM_D_JayfNE6OkXS3rGlywZSU9NKsjI9pyLPQ-lxm9y3-3tJXUWtSDhehioZ0Tqk1uVmQStRko-_tLsXc1XpZ-7HsRgCfSn2a3ACdtKivSfDuONTzc06qNuhd03fk1-WxOP38iWG5z4ytxJwatBRQCVTFtZ9EA1-EGOp2lRtnixSPIJzJErO0QexfV5PE3k8d_dzsBxWSw"
//        remoteDataSource.searchMerchants(SearchMerchantOptions(null, "1", "10"))
//        remoteDataSource.getMerchantDetails("6588000000610659")
        remoteDataSource.fetchTerminals("6588000000610659")
//        remoteDataSource.fetchTerminals("6588000001023613") // No terminals available -> empty body
    }

    private fun initSdkWrapper() {
        val apiKey = encryptedPrefs.getApiKey()
        val publicKey = encryptedPrefs.getPublicKey()
        ClearentWrapper.initializeSDK(
            applicationContext,
            Constants.BASE_URL_SANDBOX,
            publicKey,
            apiKey
        )
    }
}